### ISSUE TITLE
Where would H2 database store data?

### ISSUE THREAD

**Issue by lplpkkk** [spring-guides/gs-relational-data-access#12]
hello, I am confused that would the H2 database disappear after this app finish? Could I store these data in my own computer? 

thanks for help!!

**Comment by dsyer** [comment]
H2 is an in-memory database. I think you can ask it to dump data to disk if you initialize it with the right URL. Why not look at the documentation here: http://www.h2database.com/html/main.html?

**Comment by lplpkkk** [comment]
thanks! Is "Embedded" means "In memory"? 

still a little confused

**Comment by gregturn** [comment]
In-memory doesn't equal embedded. In-memory runs inside the memory of the app. Embedded means that the app controls it. For example, embedded ActiveMQ or embedded Tomcat don't necessarily use the same memory space, but can be started and stopped by the app and not require additional setup outside the app.

**Comment by lplpkkk** [comment]
got it! thanks!
