### ISSUE TITLE
Unresolved directive in <stdin> on Spring Docs

### ISSUE THREAD

**Issue by tiagopedutti** [spring-guides/gs-relational-data-access#26]
Hello!
I was reading the guides on [spring.io](https://spring.io/guides/gs/relational-data-access/) and I notice that the files included in ASCII Doctors are throwing an error and I can't see the code snippet unless I access the file directly here in the repo.

Follow the evidence below:
![image](https://user-images.githubusercontent.com/1340024/100926592-753a8000-34c2-11eb-8ad1-4fd5f945a3d6.png)

**Comment by Buzzardo** [comment]
Fixed by a more recent PR. Thanks for letting us know, though.
