### ISSUE TITLE
The query-method used in this example is deprecated

### ISSUE THREAD

**Issue by lehnharrt** [spring-guides/gs-relational-data-access#28]
<img width="685" alt="Bildschirmfoto 2021-05-14 um 11 05 37" src="https://user-images.githubusercontent.com/17672730/118248201-547c4a80-b4a4-11eb-8aea-3f6c848fe3c6.png">
Please change the query-example to a non-deprecated method.

**Comment by gilles-phan** [comment]
I create a more detailled ticket.
You can switch the 2nd and 3rd param to fix it. :)

**Comment by Buzzardo** [comment]
Once https://github.com/spring-guides/gs-relational-data-access/pull/34 is merged, this will be fixed. I'll leave it open until that fix is merged.
