### ISSUE TITLE
Upgrade Spring Boot to the Latest Version

### ISSUE THREAD

**Issue by robertmcnees** [spring-guides/gs-relational-data-access#36]
Update the guide to use the most recent Spring Boot version.

Files that require changes are:
```
initial/build.gradle
initial/pom.xml
complete/build.gradle
complete/pom.xml
```

**Comment by 43v3rn88b** [comment]
wanted to submit a PR

**Comment by robertmcnees** [comment]
Closing this issue as dependabot is now configured in this project for ongoing version updates.
