### ISSUE TITLE
Remove unused CI files

### ISSUE THREAD

**Issue by robertmcnees** [spring-guides/gs-relational-data-access#40]
The file `test/run.sh` is no longer required. This file and the `test` directory can be deleted.

The file was originally used for Jenkins CI. Now that this project has been converted to GitHub Actions, this file can be removed.

**Comment by Aysha-py** [comment]
Hi @robertmcnees , Kindly assign this issue to e, I will love to work on it.

**Comment by robertmcnees** [comment]
Hi @Aysha-py. We typically don't assign issues and instead accept the first valid PR that comes through. Please feel free to submit a PR.

As a note, this is an issue I'm opening in multiple `spring-guides` repositories. If you don't get a chance to contribute with a PR for this issue there are other issues like it.

**Comment by Aysha-py** [comment]
Okay, thank you. I will check it out and create a PR.

**Comment by Aysha-py** [comment]
@robertmcnees I just created a PR for this issue. Thanks

**Comment by robertmcnees** [comment]
Thanks! I see that it was merged. I will close this issue.
