### ISSUE TITLE
"jdbc:h2:mem" doesn't work with Spring Boot 1.2.0.RC2.

### ISSUE THREAD

**Issue by izeye** [spring-guides/gs-relational-data-access#7]
"jdbc:h2:mem" doesn't work with Spring Boot 1.2.0.RC2.

"jdbc:h2:mem" works fine with "com.h2database:h2:1.3.176",

but it doesn't work with "com.h2database:h2:1.4.182".

Spring Boot 1.2.0.RC2 uses "com.h2database:h2:1.4.182".

So I guess "jdbc:h2:mem" needs to be changed to something like "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1".

**Comment by gregturn** [comment]
@izeye Sorry it took my awhile to clean up this guide. Hopefully, it's a bit more up-to-date and using Spring Boot conventions.

**Comment by izeye** [comment]
@gregturn No, problem. Thanks for the update :-)
